[package]
name = "domoloom"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
clap = { version = "4.3", features = ["derive"] }
log = "0.4"
env_logger = "0.10"
colored = "2.0"
chrono = "0.4"